# Generated by Django 3.0.8 on 2021-11-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Physician', 'Physician')], max_length=50, null=True),
        ),
    ]
