# Generated by Django 3.0.8 on 2021-11-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('Mentor', 'Mentor'), ('User', 'User')], max_length=50, null=True),
        ),
    ]
